import { DataSource } from 'typeorm';
import { Role } from '../../../modules/users/entities/role.entity';

export const ROLE_IDS = {
  STUDENT: '550e8400-e29b-41d4-a716-446655440001',
  TEACHER: '550e8400-e29b-41d4-a716-446655440002',
  ADMIN: '550e8400-e29b-41d4-a716-446655440003',
  UPLOADER: '550e8400-e29b-41d4-a716-446655440004',
};

export const rolesData: Partial<Role>[] = [
  {
    id: ROLE_IDS.STUDENT,
    name: 'student',
    displayName: 'Học viên',
    description: 'Vai trò học viên - có thể làm bài tập, thi thử, xem lịch sử và thống kê học tập',
    permissions: [
      'practice.reading',
      'practice.listening',
      'practice.writing',
      'practice.speaking',
      'exam.take',
      'exam.mock',
      'exam.virtual',
      'history.view',
      'statistics.view',
      'documents.view',
      'documents.download',
      'assignments.view',
      'assignments.submit',
      'ai-assistant.chat',
      'ai-grading.submit',
      'profile.view',
      'profile.edit',
      'notifications.view',
      'goals.view',
      'goals.create',
      'blog.read',
      'messages.send',
      'messages.receive',
    ],
    isActive: true,
  },
  {
    id: ROLE_IDS.TEACHER,
    name: 'teacher',
    displayName: 'Giáo viên',
    description: 'Vai trò giáo viên - có thể giao bài tập, chấm bài, quản lý lớp học và theo dõi tiến độ học sinh',
    permissions: [
      'practice.reading',
      'practice.listening',
      'practice.writing',
      'practice.speaking',
      'exam.take',
      'exam.mock',
      'exam.virtual',
      'history.view',
      'statistics.view',
      'documents.view',
      'documents.download',
      'documents.upload',
      'assignments.view',
      'assignments.create',
      'assignments.assign',
      'assignments.grade',
      'assignments.feedback',
      'class.view',
      'class.create',
      'class.manage',
      'class.attendance',
      'students.view',
      'students.progress',
      'goals.view',
      'goals.create',
      'goals.assign',
      'ai-assistant.chat',
      'ai-grading.review',
      'profile.view',
      'profile.edit',
      'notifications.view',
      'notifications.send',
      'blog.read',
      'blog.write',
      'messages.send',
      'messages.receive',
      'reports.generate',
      'reports.export',
    ],
    isActive: true,
  },
  {
    id: ROLE_IDS.ADMIN,
    name: 'admin',
    displayName: 'Quản trị viên',
    description: 'Vai trò quản trị viên - có toàn quyền quản lý hệ thống, người dùng và nội dung',
    permissions: [
      'practice.reading',
      'practice.listening',
      'practice.writing',
      'practice.speaking',
      'exam.take',
      'exam.mock',
      'exam.virtual',
      'history.view',
      'statistics.view',
      'statistics.all',
      'documents.view',
      'documents.download',
      'documents.upload',
      'documents.manage',
      'documents.delete',
      'assignments.view',
      'assignments.create',
      'assignments.assign',
      'assignments.grade',
      'assignments.manage',
      'assignments.delete',
      'class.view',
      'class.create',
      'class.manage',
      'class.delete',
      'class.attendance',
      'users.view',
      'users.create',
      'users.edit',
      'users.delete',
      'users.ban',
      'roles.view',
      'roles.assign',
      'students.view',
      'students.progress',
      'teachers.view',
      'teachers.manage',
      'goals.view',
      'goals.create',
      'goals.assign',
      'goals.delete',
      'ai-assistant.chat',
      'ai-assistant.configure',
      'ai-grading.review',
      'ai-grading.configure',
      'profile.view',
      'profile.edit',
      'notifications.view',
      'notifications.send',
      'notifications.broadcast',
      'blog.read',
      'blog.write',
      'blog.edit',
      'blog.delete',
      'blog.publish',
      'messages.send',
      'messages.receive',
      'messages.moderate',
      'reports.generate',
      'reports.export',
      'reports.all',
      'system.settings',
      'system.backup',
      'system.logs',
      'analytics.view',
    ],
    isActive: true,
  },
  {
    id: ROLE_IDS.UPLOADER,
    name: 'uploader',
    displayName: 'Người tải lên',
    description: 'Vai trò người tải lên - chuyên trách upload và quản lý đề thi, tài liệu học tập',
    permissions: [
      'practice.reading',
      'practice.listening',
      'practice.writing',
      'practice.speaking',
      'exam.take',
      'exam.mock',
      'exam.virtual',
      'history.view',
      'statistics.view',
      'documents.view',
      'documents.download',
      'documents.upload',
      'documents.manage',
      'documents.categorize',
      'exercises.upload',
      'exercises.edit',
      'exercises.manage',
      'exams.upload',
      'exams.edit',
      'exams.manage',
      'materials.upload',
      'materials.edit',
      'materials.manage',
      'audio.upload',
      'audio.manage',
      'images.upload',
      'images.manage',
      'ai-assistant.chat',
      'profile.view',
      'profile.edit',
      'notifications.view',
      'blog.read',
      'messages.send',
      'messages.receive',
      'reports.content',
    ],
    isActive: true,
  },
];

export async function seedRoles(dataSource: DataSource): Promise<void> {
  const roleRepo = dataSource.getRepository(Role);

  for (const roleData of rolesData) {
    const existing = await roleRepo.findOne({ where: { id: roleData.id } });
    
    if (!existing) {
      await roleRepo.save(roleRepo.create(roleData));
      console.log(`✅ Created role: ${roleData.name}`);
    } else {
      // Update existing role with new permissions
      await roleRepo.update(existing.id, roleData);
      console.log(`🔄 Updated role: ${roleData.name}`);
    }
  }

  console.log('🎉 Roles seeding completed!');
}
