import { DataSource } from 'typeorm';
import { User, UserStatus } from '../../../modules/users/entities/user.entity';
import { UserProfile } from '../../../modules/users/entities/user-profile.entity';
import { UserStats } from '../../../modules/users/entities/user-stats.entity';
import { UserSettings } from '../../../modules/users/entities/user-settings.entity';
import { ROLE_IDS } from './role.seed';
import * as bcrypt from 'bcrypt';

// Fixed UUIDs for dummy users
export const USER_IDS = {
  // Admins
  ADMIN_SUPER: '11111111-1111-1111-1111-111111111001',
  ADMIN_CONTENT: '11111111-1111-1111-1111-111111111002',

  // Teachers
  TEACHER_NGUYEN: '22222222-2222-2222-2222-222222222001',
  TEACHER_TRAN: '22222222-2222-2222-2222-222222222002',
  TEACHER_LE: '22222222-2222-2222-2222-222222222003',

  // Uploaders
  UPLOADER_MAIN: '33333333-3333-3333-3333-333333333001',
  UPLOADER_CONTENT: '33333333-3333-3333-3333-333333333002',

  // Students
  STUDENT_01: '44444444-4444-4444-4444-444444444001',
  STUDENT_02: '44444444-4444-4444-4444-444444444002',
  STUDENT_03: '44444444-4444-4444-4444-444444444003',
  STUDENT_04: '44444444-4444-4444-4444-444444444004',
  STUDENT_05: '44444444-4444-4444-4444-444444444005',
  STUDENT_06: '44444444-4444-4444-4444-444444444006',
  STUDENT_07: '44444444-4444-4444-4444-444444444007',
  STUDENT_08: '44444444-4444-4444-4444-444444444008',
  STUDENT_09: '44444444-4444-4444-4444-444444444009',
  STUDENT_10: '44444444-4444-4444-4444-444444444010',
};

// Default password for all dummy users: "password123"
const DEFAULT_PASSWORD_HASH = '$2b$10$8K1p/a0dL1LXMIgoEDFrwOfw1E3tZSgZAhLxE1mA1oHrPLMrHIzUe';

interface UserSeedData {
  user: Partial<User>;
  profile: Partial<UserProfile>;
  stats: Partial<UserStats>;
  settings: Partial<UserSettings>;
}

const usersData: UserSeedData[] = [
  // =====================
  // ADMIN USERS
  // =====================
  {
    user: {
      id: USER_IDS.ADMIN_SUPER,
      email: 'admin@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Super',
      lastName: 'Admin',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-01-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.ADMIN,
    },
    profile: {
      phone: '0901234567',
      location: 'Hà Nội',
      bio: 'Quản trị viên hệ thống VSTEP',
      currentLevel: 'C1',
      targetLevel: 'C1',
    },
    stats: {
      totalHours: 100,
      testsCompleted: 50,
      currentStreak: 30,
      longestStreak: 60,
      averageScore: 8.5,
      xp: 10000,
      level: 20,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      profilePublic: false,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.ADMIN_CONTENT,
      email: 'content.admin@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Content',
      lastName: 'Manager',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=contentadmin',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-02-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.ADMIN,
    },
    profile: {
      phone: '0901234568',
      location: 'TP. Hồ Chí Minh',
      bio: 'Quản lý nội dung và ngân hàng đề thi',
      currentLevel: 'B2',
      targetLevel: 'C1',
    },
    stats: {
      totalHours: 50,
      testsCompleted: 20,
      currentStreak: 10,
      longestStreak: 30,
      averageScore: 7.5,
      xp: 5000,
      level: 12,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: false,
      profilePublic: false,
      language: 'vi',
      theme: 'dark',
    },
  },

  // =====================
  // TEACHER USERS
  // =====================
  {
    user: {
      id: USER_IDS.TEACHER_NGUYEN,
      email: 'nguyen.teacher@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Nguyễn Văn',
      lastName: 'An',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=teacher1',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-01-15'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.TEACHER,
    },
    profile: {
      phone: '0912345678',
      dateOfBirth: new Date('1985-05-15'),
      location: 'Hà Nội',
      bio: 'Giáo viên tiếng Anh với 10 năm kinh nghiệm, chuyên luyện thi VSTEP B2-C1',
      currentLevel: 'C1',
      targetLevel: 'C1',
      studyGoalMinutes: 60,
    },
    stats: {
      totalHours: 200,
      testsCompleted: 100,
      currentStreak: 45,
      longestStreak: 90,
      averageScore: 9.0,
      xp: 15000,
      level: 25,
      readingScore: 9,
      listeningScore: 9,
      writingScore: 8,
      speakingScore: 9,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: false,
      dailyGoalMinutes: 60,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.TEACHER_TRAN,
      email: 'tran.teacher@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Trần Thị',
      lastName: 'Bình',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=teacher2',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-02-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.TEACHER,
    },
    profile: {
      phone: '0912345679',
      dateOfBirth: new Date('1990-08-20'),
      location: 'Đà Nẵng',
      bio: 'Giáo viên chuyên về Speaking và Writing, IELTS 8.0',
      currentLevel: 'C1',
      targetLevel: 'C1',
      studyGoalMinutes: 45,
    },
    stats: {
      totalHours: 150,
      testsCompleted: 75,
      currentStreak: 20,
      longestStreak: 60,
      averageScore: 8.5,
      xp: 12000,
      level: 22,
      readingScore: 8,
      listeningScore: 8,
      writingScore: 9,
      speakingScore: 9,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 45,
      language: 'vi',
      theme: 'system',
    },
  },
  {
    user: {
      id: USER_IDS.TEACHER_LE,
      email: 'le.teacher@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Lê Minh',
      lastName: 'Cường',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=teacher3',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-03-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.TEACHER,
    },
    profile: {
      phone: '0912345680',
      dateOfBirth: new Date('1988-12-10'),
      location: 'TP. Hồ Chí Minh',
      bio: 'Chuyên gia luyện thi Reading và Listening, giảng viên đại học',
      currentLevel: 'C1',
      targetLevel: 'C1',
      studyGoalMinutes: 30,
    },
    stats: {
      totalHours: 180,
      testsCompleted: 80,
      currentStreak: 15,
      longestStreak: 45,
      averageScore: 8.8,
      xp: 13000,
      level: 23,
      readingScore: 9,
      listeningScore: 9,
      writingScore: 8,
      speakingScore: 8,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: false,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 30,
      language: 'en',
      theme: 'dark',
    },
  },

  // =====================
  // UPLOADER USERS
  // =====================
  {
    user: {
      id: USER_IDS.UPLOADER_MAIN,
      email: 'uploader@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Phạm Văn',
      lastName: 'Dũng',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=uploader1',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-01-20'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.UPLOADER,
    },
    profile: {
      phone: '0923456789',
      location: 'Hà Nội',
      bio: 'Chuyên viên upload và quản lý nội dung đề thi',
      currentLevel: 'B2',
      targetLevel: 'C1',
    },
    stats: {
      totalHours: 30,
      testsCompleted: 10,
      currentStreak: 5,
      longestStreak: 15,
      averageScore: 7.0,
      xp: 3000,
      level: 8,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      profilePublic: false,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.UPLOADER_CONTENT,
      email: 'content.uploader@vstep.edu.vn',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Hoàng Thị',
      lastName: 'Hoa',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=uploader2',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-02-15'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.UPLOADER,
    },
    profile: {
      phone: '0923456790',
      location: 'TP. Hồ Chí Minh',
      bio: 'Chuyên viên nội dung và biên soạn tài liệu',
      currentLevel: 'B2',
      targetLevel: 'B2',
    },
    stats: {
      totalHours: 25,
      testsCompleted: 8,
      currentStreak: 3,
      longestStreak: 10,
      averageScore: 7.2,
      xp: 2500,
      level: 7,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: false,
      profilePublic: false,
      language: 'vi',
      theme: 'system',
    },
  },

  // =====================
  // STUDENT USERS
  // =====================
  {
    user: {
      id: USER_IDS.STUDENT_01,
      email: 'student01@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Nguyễn Thị',
      lastName: 'Mai',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student1',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-06-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567890',
      dateOfBirth: new Date('2000-03-15'),
      location: 'Hà Nội',
      bio: 'Sinh viên năm 3, đang chuẩn bị thi VSTEP B2',
      currentLevel: 'B1',
      targetLevel: 'B2',
      targetDate: new Date('2025-06-30'),
      studyGoalMinutes: 60,
    },
    stats: {
      totalHours: 45,
      testsCompleted: 25,
      currentStreak: 12,
      longestStreak: 20,
      averageScore: 6.5,
      xp: 4500,
      level: 10,
      readingScore: 7,
      listeningScore: 6,
      writingScore: 6,
      speakingScore: 7,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 60,
      autoPlayAudio: true,
      playbackSpeed: 1.0,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_02,
      email: 'student02@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Trần Văn',
      lastName: 'Hùng',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student2',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-06-15'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567891',
      dateOfBirth: new Date('1998-07-20'),
      location: 'TP. Hồ Chí Minh',
      bio: 'Nhân viên văn phòng, cần VSTEP B2 để thăng tiến',
      currentLevel: 'B1',
      targetLevel: 'B2',
      targetDate: new Date('2025-03-31'),
      studyGoalMinutes: 45,
    },
    stats: {
      totalHours: 60,
      testsCompleted: 35,
      currentStreak: 25,
      longestStreak: 35,
      averageScore: 7.0,
      xp: 6000,
      level: 13,
      readingScore: 7,
      listeningScore: 7,
      writingScore: 7,
      speakingScore: 6,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 45,
      autoPlayAudio: false,
      playbackSpeed: 1.25,
      language: 'vi',
      theme: 'dark',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_03,
      email: 'student03@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Lê Thị',
      lastName: 'Lan',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student3',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-07-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567892',
      dateOfBirth: new Date('2001-11-05'),
      location: 'Đà Nẵng',
      bio: 'Sinh viên đại học, mục tiêu đạt C1 để du học',
      currentLevel: 'B2',
      targetLevel: 'C1',
      targetDate: new Date('2025-12-31'),
      studyGoalMinutes: 90,
    },
    stats: {
      totalHours: 80,
      testsCompleted: 50,
      currentStreak: 30,
      longestStreak: 45,
      averageScore: 7.8,
      xp: 8500,
      level: 17,
      readingScore: 8,
      listeningScore: 8,
      writingScore: 7,
      speakingScore: 8,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 90,
      autoPlayAudio: true,
      playbackSpeed: 1.0,
      language: 'en',
      theme: 'system',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_04,
      email: 'student04@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Phạm Minh',
      lastName: 'Tuấn',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student4',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-07-15'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567893',
      dateOfBirth: new Date('1995-04-12'),
      location: 'Hải Phòng',
      bio: 'Giáo viên tiểu học, cần nâng cao trình độ tiếng Anh',
      currentLevel: 'A2',
      targetLevel: 'B1',
      targetDate: new Date('2025-06-30'),
      studyGoalMinutes: 30,
    },
    stats: {
      totalHours: 20,
      testsCompleted: 10,
      currentStreak: 5,
      longestStreak: 10,
      averageScore: 5.5,
      xp: 2000,
      level: 5,
      readingScore: 6,
      listeningScore: 5,
      writingScore: 5,
      speakingScore: 5,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: false,
      showProgress: false,
      showOnLeaderboard: false,
      dailyGoalMinutes: 30,
      autoPlayAudio: true,
      playbackSpeed: 0.75,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_05,
      email: 'student05@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Hoàng Văn',
      lastName: 'Nam',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student5',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-08-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567894',
      dateOfBirth: new Date('1999-09-25'),
      location: 'Cần Thơ',
      bio: 'Kỹ sư IT, cần tiếng Anh cho công việc',
      currentLevel: 'B1',
      targetLevel: 'B2',
      targetDate: new Date('2025-09-30'),
      studyGoalMinutes: 45,
    },
    stats: {
      totalHours: 35,
      testsCompleted: 18,
      currentStreak: 8,
      longestStreak: 15,
      averageScore: 6.8,
      xp: 3800,
      level: 9,
      readingScore: 7,
      listeningScore: 7,
      writingScore: 6,
      speakingScore: 6,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: false,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: false,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 45,
      autoPlayAudio: true,
      playbackSpeed: 1.0,
      language: 'vi',
      theme: 'dark',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_06,
      email: 'student06@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Vũ Thị',
      lastName: 'Hương',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student6',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-08-15'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567895',
      dateOfBirth: new Date('2002-01-30'),
      location: 'Nghệ An',
      bio: 'Học sinh lớp 12, chuẩn bị thi đại học',
      currentLevel: 'A2',
      targetLevel: 'B1',
      targetDate: new Date('2025-05-31'),
      studyGoalMinutes: 60,
    },
    stats: {
      totalHours: 25,
      testsCompleted: 12,
      currentStreak: 15,
      longestStreak: 20,
      averageScore: 5.8,
      xp: 2500,
      level: 6,
      readingScore: 6,
      listeningScore: 5,
      writingScore: 6,
      speakingScore: 5,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 60,
      autoPlayAudio: true,
      playbackSpeed: 0.75,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_07,
      email: 'student07@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Đỗ Quang',
      lastName: 'Minh',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student7',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-09-01'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567896',
      dateOfBirth: new Date('1997-06-18'),
      location: 'Bình Dương',
      bio: 'Nhân viên marketing, cần tiếng Anh giao tiếp',
      currentLevel: 'B1',
      targetLevel: 'B2',
      targetDate: new Date('2025-08-31'),
      studyGoalMinutes: 30,
    },
    stats: {
      totalHours: 40,
      testsCompleted: 22,
      currentStreak: 10,
      longestStreak: 18,
      averageScore: 6.5,
      xp: 4000,
      level: 9,
      readingScore: 6,
      listeningScore: 7,
      writingScore: 6,
      speakingScore: 7,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: false,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 30,
      autoPlayAudio: false,
      playbackSpeed: 1.25,
      language: 'vi',
      theme: 'system',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_08,
      email: 'student08@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Bùi Thị',
      lastName: 'Ngọc',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student8',
      status: UserStatus.ACTIVE,
      emailVerifiedAt: new Date('2024-09-15'),
      lastLoginAt: new Date(),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567897',
      dateOfBirth: new Date('2000-12-08'),
      location: 'Quảng Ninh',
      bio: 'Nhân viên du lịch, cần tiếng Anh phục vụ khách nước ngoài',
      currentLevel: 'B1',
      targetLevel: 'B2',
      targetDate: new Date('2025-04-30'),
      studyGoalMinutes: 45,
    },
    stats: {
      totalHours: 55,
      testsCompleted: 30,
      currentStreak: 20,
      longestStreak: 28,
      averageScore: 7.2,
      xp: 5500,
      level: 12,
      readingScore: 7,
      listeningScore: 8,
      writingScore: 7,
      speakingScore: 7,
      lastStudyDate: new Date(),
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 45,
      autoPlayAudio: true,
      playbackSpeed: 1.0,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_09,
      email: 'student09@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Ngô Văn',
      lastName: 'Thành',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student9',
      status: UserStatus.PENDING,
      emailVerifiedAt: null,
      lastLoginAt: null,
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567898',
      dateOfBirth: new Date('1996-02-14'),
      location: 'Thanh Hóa',
      bio: 'Mới đăng ký, chưa xác minh email',
      currentLevel: null,
      targetLevel: 'B1',
      studyGoalMinutes: 30,
    },
    stats: {
      totalHours: 0,
      testsCompleted: 0,
      currentStreak: 0,
      longestStreak: 0,
      averageScore: 0,
      xp: 0,
      level: 1,
    },
    settings: {
      emailNotifications: true,
      pushNotifications: true,
      studyReminders: true,
      weeklyReport: true,
      achievementAlerts: true,
      profilePublic: true,
      showProgress: true,
      showOnLeaderboard: true,
      dailyGoalMinutes: 30,
      language: 'vi',
      theme: 'light',
    },
  },
  {
    user: {
      id: USER_IDS.STUDENT_10,
      email: 'student10@gmail.com',
      password: DEFAULT_PASSWORD_HASH,
      firstName: 'Đinh Thị',
      lastName: 'Yến',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student10',
      status: UserStatus.INACTIVE,
      emailVerifiedAt: new Date('2024-03-01'),
      lastLoginAt: new Date('2024-06-01'),
      roleId: ROLE_IDS.STUDENT,
    },
    profile: {
      phone: '0934567899',
      dateOfBirth: new Date('1994-08-22'),
      location: 'Vũng Tàu',
      bio: 'Đã hoàn thành khóa học, tạm dừng',
      currentLevel: 'B2',
      targetLevel: 'B2',
      studyGoalMinutes: 30,
    },
    stats: {
      totalHours: 100,
      testsCompleted: 60,
      currentStreak: 0,
      longestStreak: 50,
      averageScore: 7.5,
      xp: 9000,
      level: 18,
      readingScore: 8,
      listeningScore: 7,
      writingScore: 7,
      speakingScore: 8,
      lastStudyDate: new Date('2024-06-01'),
    },
    settings: {
      emailNotifications: false,
      pushNotifications: false,
      studyReminders: false,
      weeklyReport: false,
      achievementAlerts: false,
      profilePublic: false,
      showProgress: false,
      showOnLeaderboard: false,
      dailyGoalMinutes: 30,
      language: 'vi',
      theme: 'dark',
    },
  },
];

export async function seedUsers(dataSource: DataSource): Promise<void> {
  const userRepo = dataSource.getRepository(User);
  const profileRepo = dataSource.getRepository(UserProfile);
  const statsRepo = dataSource.getRepository(UserStats);
  const settingsRepo = dataSource.getRepository(UserSettings);

  console.log('📦 Seeding users...');

  for (const userData of usersData) {
    // Check if user already exists
    const existingUser = await userRepo.findOne({ where: { id: userData.user.id } });
    
    if (existingUser) {
      console.log(`⏭️  User ${userData.user.email} already exists, skipping...`);
      continue;
    }

    // Create user
    const user = userRepo.create(userData.user);
    await userRepo.save(user);
    console.log(`✅ Created user: ${user.email} (${user.firstName} ${user.lastName})`);

    // Create profile
    const profile = profileRepo.create({
      ...userData.profile,
      userId: user.id,
    });
    await profileRepo.save(profile);

    // Create stats
    const stats = statsRepo.create({
      ...userData.stats,
      userId: user.id,
    });
    await statsRepo.save(stats);

    // Create settings
    const settings = settingsRepo.create({
      ...userData.settings,
      userId: user.id,
    });
    await settingsRepo.save(settings);
  }

  console.log('🎉 Users seeding completed!');
}
